// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ApplicationLogo: typeof import('./Components/ApplicationLogo.vue')['default']
    Button: typeof import('./Components/Button.vue')['default']
    Checkbox: typeof import('./Components/Checkbox.vue')['default']
    Dropdown: typeof import('./Components/Dropdown.vue')['default']
    DropdownLink: typeof import('./Components/DropdownLink.vue')['default']
    Head: typeof import('@inertiajs/inertia-vue3')['Head']
    Input: typeof import('./Components/Input.vue')['default']
    InputError: typeof import('./Components/InputError.vue')['default']
    Label: typeof import('./Components/Label.vue')['default']
    Link: typeof import('@inertiajs/inertia-vue3')['Link']
    NavLink: typeof import('./Components/NavLink.vue')['default']
    ResponsiveNavLink: typeof import('./Components/ResponsiveNavLink.vue')['default']
  }
}
